name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -s -o /dev/null "https://movierecommendersystem-jkpk2hztekwjdhbmpvjmr8.streamlit.app/"
